apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::694655080513:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-157UHKUJ8TU7L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::694655080513:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-03T16:01:24Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-03T16:01:24Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-01-03T16:04:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2205"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: aac2beae-2922-49a7-ac01-9824f4eed26c
