apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::694655080513:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-03T10:34:19Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-03T10:34:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1530"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 10d79d13-41bf-40e9-9b4d-a9cb9087fe1a
