apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::694655080513:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-03T07:52:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-03T07:52:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1494"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a81fb930-ccc6-430e-a655-22858c18a636
